version: '3.8'

volumes:
  online-consultation:
    external: false

services:
  online-consultation:
    container_name: online-consultation
    image: praveennagaraj/online-consultation
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 4000:4000
    env_file:
      - .env
    environment:
      - PORT=${PORT}
      - ENVIRONMENT=${ENVIRONMENT}
      - MONGO_URI=${MONGO_URI}
      - TWILIO_ACCOUNT_SID=${TWILIO_ACCOUNT_SID}
      - TWILIO_AUTH_TOKEN=${TWILIO_AUTH_TOKEN}
      - TWILIO_FROM_NUMBER=${TWILIO_FROM_NUMBER}
      - ACCESS_SECRET=${ACCESS_SECRET}
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_USERNAME=${SMTP_USERNAME}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
      - SENDER_EMAIL=${SENDER_EMAIL}
      - SMTP_NOREPLY_EMAIL=${SMTP_NOREPLY_EMAIL}
      - CLIENT_VERIFY_EMAIL_LINK=${CLIENT_VERIFY_EMAIL_LINK}
      - CLIENT_EMAIL_SIGNIN_LINK=${CLIENT_EMAIL_SIGNIN_LINK}
      - CLIENT_VERIFY_FORGOT_PASSWORD_LINK=${CLIENT_VERIFY_FORGOT_PASSWORD_LINK}
      - CLIENT_DOCTOR_ACTIVATE_ACCOUNT_LINK=${CLIENT_DOCTOR_ACTIVATE_ACCOUNT_LINK}
      - S3_BUCKET_NAME=${S3_BUCKET_NAME}
      - S3_BUCKET_REGION=${S3_BUCKET_REGION}
      - S3_ACCESS_KEY_ID=${S3_ACCESS_KEY_ID}
      - S3_SECRET_ACCESS=${S3_SECRET_ACCESS}
      - S3_ACCESS_BASEURL=${S3_ACCESS_BASEURL}
      - STRIPE_PUBLISHABLE_KEY=${STRIPE_PUBLISHABLE_KEY}
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
      - RAZOR_PAY_KEY_ID=${RAZOR_PAY_KEY_ID}
      - RAZOR_PAY_KEY_SECRET=${RAZOR_PAY_KEY_SECRET}
    volumes:
      - .:/src/app
    restart: unless-stopped
    depends_on:
      - mongo

  mongo:
    image: mongo
    restart: unless-stopped
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASS}
    volumes:
      - online-consultation:/data/db
