version: '3.8'

volumes:
  online-consultation-prod:
    external: false

services:
  online-consultation-prod:
    container_name: online-consultation-prod
    image: praveennagaraj/online-consultation
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    env_file:
      - .env.prod
    environment:
      - PORT=${PORT}
      - ENVIRONMENT=${ENVIRONMENT}
      - MONGO_URI=${MONGO_URI}
      - ACCESS_SECRET=${ACCESS_SECRET}
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_USERNAME=${SMTP_USERNAME}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
      - SENDER_EMAIL=${SENDER_EMAIL}
      - SMTP_NOREPLY_EMAIL=${SMTP_NOREPLY_EMAIL}
      - CLIENT_VERIFY_EMAIL_LINK=${CLIENT_VERIFY_EMAIL_LINK}
      - CLIENT_EMAIL_SIGNIN_LINK=${CLIENT_EMAIL_SIGNIN_LINK}
      - CLIENT_VERIFY_FORGOT_PASSWORD_LINK=${CLIENT_VERIFY_FORGOT_PASSWORD_LINK}
      - CLIENT_DOCTOR_ACTIVATE_ACCOUNT_LINK=${CLIENT_DOCTOR_ACTIVATE_ACCOUNT_LINK}
      - S3_BUCKET_NAME=${S3_BUCKET_NAME}
      - S3_BUCKET_REGION=${S3_BUCKET_REGION}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS=${AWS_SECRET_ACCESS}
      - S3_ACCESS_BASEURL=${S3_ACCESS_BASEURL}
      - STRIPE_PUBLISHABLE_KEY=${STRIPE_PUBLISHABLE_KEY}
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
      - RAZOR_PAY_KEY_ID=${RAZOR_PAY_KEY_ID}
      - RAZOR_PAY_KEY_SECRET=${RAZOR_PAY_KEY_SECRET}
    volumes:
      - .:/src/app
